Add GitHub action for code scanner
awslabs/Renate pull request #71
Opened 2022-12-15 15:26 UTC by 610v4nn1

Add GitHub action for code scanner

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-15 18:45 UTC, wistuba requested changes
all knowledge taken from https://github.com/github/codeql-action

2022-12-15 18:45 UTC, wistuba commented on .github/workflows/codeql.yml
> +      contents: read
only required for private repos

2022-12-15 18:45 UTC, wistuba commented on .github/workflows/codeql.yml
> +        language: [ 'python' ]
we can drop this

2022-12-15 18:45 UTC, wistuba commented on .github/workflows/codeql.yml
> +    branches: [ "main", dev ]
why the "?

2022-12-15 18:45 UTC, wistuba commented on .github/workflows/codeql.yml
> +        category: "/language:${{matrix.language}}"
I don't think we need this

2022-12-15 18:45 UTC, wistuba commented on .github/workflows/codeql.yml
> +        languages: ${{ matrix.language }}
python

2022-12-15 18:45 UTC, wistuba commented on .github/workflows/codeql.yml
> +      uses: github/codeql-action/autobuild@v2
do we need this for python?

2022-12-16 09:22 UTC, lballes commented on .github/workflows/codeql.yml
> +        category: "/language:${{matrix.language}}"
What about this? Do we need it?

2022-12-16 09:22 UTC, lballes commented on .github/workflows/codeql.yml
> +        languages: ${{ matrix.language }}
Why not just python?

2022-12-16 11:04 UTC, lballes approved these changes

2022-12-16 15:36 UTC, merged